services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: lms-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "LmsPassw0rd#2026"
    ports:
      - "11433:1433"
    volumes:
      - lms_sqlserver_data:/var/opt/mssql

volumes:
  lms_sqlserver_data:
