// <auto-generated />
using System;
using LMS.Api.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LMS.Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260621111530_AddCourseRejectReason")]
    partial class AddCourseRejectReason
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LMS.Api.Domain.Entities.BaiHoc", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("ChoXemTruoc")
                        .HasColumnType("bit");

                    b.Property<string>("ChuongHocId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("DaXuatBan")
                        .HasColumnType("bit");

                    b.Property<string>("FileUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IllustrationUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KhoaHocId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ThoiLuongGiay")
                        .HasColumnType("int");

                    b.Property<int>("ThuTu")
                        .HasColumnType("int");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("DRAFT");

                    b.Property<string>("VideoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ChuongHocId");

                    b.HasIndex("KhoaHocId");

                    b.ToTable("BaiHoc", (string)null);
                });

            modelBuilder.Entity("LMS.Api.Domain.Entities.BaiKiemTra", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BaiHocId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("DiemDat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(80);

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BaiHocId")
                        .IsUnique();

                    b.ToTable("BaiKiemTra", (string)null);
                });

            modelBuilder.Entity("LMS.Api.Domain.Entities.BaiNopKiemTra", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BaiKiemTraId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DapAn")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<bool>("Dat")
                        .HasColumnType("bit");

                    b.Property<double>("Diem")
                        .HasColumnType("float");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiDungId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("BaiKiemTraId");

                    b.HasIndex("NguoiDungId");

                    b.ToTable("BaiNopKiemTra", (string)null);
                });

            modelBuilder.Entity("LMS.Api.Domain.Entities.BaiTap", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BaiHocId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("ChoPhepNopFile")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("ChoPhepNopText")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("DiemToiDa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(100);

                    b.Property<string>("FileDinhKemUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GiangVienId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("HanNop")
                        .HasColumnType("datetime2");

                    b.Property<string>("KhoaHocId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BaiHocId");

                    b.HasIndex("GiangVienId");

                    b.HasIndex("KhoaHocId");

                    b.ToTable("BaiTap", (string)null);
                });

            modelBuilder.Entity("LMS.Api.Domain.Entities.BinhLuan", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BaiHocId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BinhLuanChaId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiDungId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BaiHocId");

                    b.HasIndex("BinhLuanChaId");

                    b.HasIndex("NguoiDungId");

                    b.ToTable("BinhLuan", (string)null);
                });

            modelBuilder.Entity("LMS.Api.Domain.Entities.CauHoiKiemTra", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BaiKiemTraId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CacLuaChon")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("DapAnDungIndex")
                        .HasColumnType("int");

                    b.Property<string>("GiaiThich")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDungCauHoi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ThuTu")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BaiKiemTraId");

                    b.ToTable("CauHoiKiemTra", (string)null);
                });

            modelBuilder.Entity("LMS.Api.Domain.Entities.ChungChi", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AnhChupHoanThanh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KhoaHocId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaXacThuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayCap")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiDungId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PdfUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoChungChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KhoaHocId");

                    b.HasIndex("NguoiDungId", "KhoaHocId")
                        .IsUnique();

                    b.ToTable("ChungChi", (string)null);
                });

            modelBuilder.Entity("LMS.Api.Domain.Entities.ChuongHoc", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("KhoaHocId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("ThuTu")
                        .HasColumnType("int");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KhoaHocId");

                    b.ToTable("ChuongHoc", (string)null);
                });

            modelBuilder.Entity("LMS.Api.Domain.Entities.CuocTroChuyen", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClassId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("KhoaHocId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("LaNhom")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("SubjectId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TieuDe")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("KhoaHocId");

                    b.HasIndex("KhoaHocId", "ClassId", "SubjectId");

                    b.ToTable("CuocTroChuyen", (string)null);
                });

            modelBuilder.Entity("LMS.Api.Domain.Entities.DangKySuKien", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("DiemDaDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayDangKy")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiDungId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SuKienId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("REGISTERED");

                    b.HasKey("Id");

                    b.HasIndex("NguoiDungId", "NgayDangKy");

                    b.HasIndex("SuKienId", "NguoiDungId")
                        .IsUnique();

                    b.ToTable("DangKySuKien", (string)null);
                });

            modelBuilder.Entity("LMS.Api.Domain.Entities.DanhGiaKhoaHoc", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BinhLuan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DiemDanhGia")
                        .HasColumnType("int");

                    b.Property<string>("KhoaHocId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiDungId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("KhoaHocId", "NgayTao");

                    b.HasIndex("NguoiDungId", "KhoaHocId")
                        .IsUnique();

                    b.HasIndex("NguoiDungId", "NgayTao");

                    b.ToTable("DanhGiaKhoaHoc", (string)null);
                });

            modelBuilder.Entity("LMS.Api.Domain.Entities.DanhMuc", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("HoatDong")
                        .HasColumnType("bit");

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("Ten")
                        .IsUnique();

                    b.ToTable("DanhMuc", (string)null);
                });

            modelBuilder.Entity("LMS.Api.Domain.Entities.DoiThuongSuKien", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("DiemYeuCau")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiDungId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PhanThuongId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TieuDeSuKien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NguoiDungId", "PhanThuongId")
                        .IsUnique();

                    b.ToTable("DoiThuongSuKien", (string)null);
                });

            modelBuilder.Entity("LMS.Api.Domain.Entities.DonMua", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("KhoaHocId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoaiTien")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("VND");

                    b.Property<string>("MaGiamGiaId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiDungId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SoTienCuoi")
                        .HasColumnType("int");

                    b.Property<int>("SoTienGiam")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("SoTienGoc")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("COMPLETED");

                    b.HasKey("Id");

                    b.HasIndex("MaGiamGiaId");

                    b.HasIndex("KhoaHocId", "NgayTao");

                    b.HasIndex("NguoiDungId", "KhoaHocId")
                        .IsUnique();

                    b.HasIndex("NguoiDungId", "NgayTao");

                    b.ToTable("DonMua", (string)null);
                });

            modelBuilder.Entity("LMS.Api.Domain.Entities.GhiDanh", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("KhoaHocId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayHoanThanh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiDungId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("TienDo")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("KhoaHocId");

                    b.HasIndex("NguoiDungId", "KhoaHocId")
                        .IsUnique();

                    b.ToTable("GhiDanh", (string)null);
                });

            modelBuilder.Entity("LMS.Api.Domain.Entities.GiaoDichVi", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DonMuaId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("KhoaHocId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoaiGiaoDich")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Metadata")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiDungId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoDuSauGiaoDich")
                        .HasColumnType("int");

                    b.Property<int>("SoTien")
                        .HasColumnType("int");

                    b.Property<string>("ThanhToanId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("COMPLETED");

                    b.HasKey("Id");

                    b.HasIndex("DonMuaId");

                    b.HasIndex("KhoaHocId");

                    b.HasIndex("ThanhToanId");

                    b.HasIndex("LoaiGiaoDich", "NgayTao");

                    b.HasIndex("NguoiDungId", "NgayTao");

                    b.ToTable("GiaoDichVi", (string)null);
                });

            modelBuilder.Entity("LMS.Api.Domain.Entities.KhoaHoc", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AnhDaiDien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChuyenMuc")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Lập trình");

                    b.Property<bool>("DaXuatBan")
                        .HasColumnType("bit");

                    b.Property<string>("DanhMucId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("DiemDanhGiaTrungBinh")
                        .HasColumnType("float");

                    b.Property<string>("DuongDanThanThien")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Gia")
                        .HasColumnType("int");

                    b.Property<string>("GiangVienId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("HangThanhVienToiThieu")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("BRONZE");

                    b.Property<string>("LyDoTuChoi")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTaChiTiet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTaNgan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayXuatBan")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoLuongDanhGia")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TongThoiLuongGiay")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("DRAFT");

                    b.Property<string>("TrinhDo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("BEGINNER");

                    b.HasKey("Id");

                    b.HasIndex("DanhMucId");

                    b.HasIndex("DuongDanThanThien")
                        .IsUnique();

                    b.HasIndex("GiangVienId");

                    b.ToTable("KhoaHoc", (string)null);
                });

            modelBuilder.Entity("LMS.Api.Domain.Entities.KhoaHocDaLuu", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("KhoaHocId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiDungId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("KhoaHocId");

                    b.HasIndex("NguoiDungId", "KhoaHocId")
                        .IsUnique();

                    b.HasIndex("NguoiDungId", "NgayTao");

                    b.ToTable("KhoaHocDaLuu", (string)null);
                });

            modelBuilder.Entity("LMS.Api.Domain.Entities.LichSuDungMaGiamGia", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DonMuaId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("KhoaHocId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaGiamGiaId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiDungId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("DonMuaId")
                        .IsUnique();

                    b.HasIndex("KhoaHocId");

                    b.HasIndex("NguoiDungId");

                    b.HasIndex("MaGiamGiaId", "NguoiDungId")
                        .IsUnique();

                    b.ToTable("LichSuDungMaGiamGia", (string)null);
                });

            modelBuilder.Entity("LMS.Api.Domain.Entities.MaGiamGia", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DiscountType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("PERCENTAGE");

                    b.Property<int>("DiscountValue")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("GiangVienId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("HoatDong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsPrivate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("KhoaHocId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("MaxDiscountAmount")
                        .HasColumnType("int");

                    b.Property<int>("MinPurchaseAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("ACTIVE");

                    b.Property<int>("UsageCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("UsageLimit")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GiangVienId");

                    b.HasIndex("KhoaHocId");

                    b.HasIndex("Ma")
                        .IsUnique();

                    b.ToTable("MaGiamGia", (string)null);
                });

            modelBuilder.Entity("LMS.Api.Domain.Entities.NguoiDung", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AnhDaiDien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CaiDat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ChuoiDangNhap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("DiemThuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("HangThanhVien")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("BRONZE");

                    b.Property<DateTime?>("LanCuoiHoatDong")
                        .HasColumnType("datetime2");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayNhanThuongBaiHocCuoi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayNhanThuongDangNhapCuoi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoDuVi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TieuSu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TongChiTieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("TuanNhanThuongMuaCuoi")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("STUDENT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("NguoiDung", (string)null);
                });

            modelBuilder.Entity("LMS.Api.Domain.Entities.NguoiNhanMaGiamGia", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("GiangVienId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaGiamGiaId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiDungId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SourceCourseId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("GiangVienId");

                    b.HasIndex("NguoiDungId");

                    b.HasIndex("SourceCourseId");

                    b.HasIndex("MaGiamGiaId", "NguoiDungId")
                        .IsUnique();

                    b.ToTable("NguoiNhanMaGiamGia", (string)null);
                });

            modelBuilder.Entity("LMS.Api.Domain.Entities.NguoiThamGiaTroChuyen", b =>
                {
                    b.Property<Guid>("CuocTroChuyenId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NguoiDungId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("DocCuoiLuc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayThamGia")
                        .HasColumnType("datetime2");

                    b.HasKey("CuocTroChuyenId", "NguoiDungId");

                    b.HasIndex("NguoiDungId");

                    b.ToTable("NguoiThamGiaTroChuyen", (string)null);
                });

            modelBuilder.Entity("LMS.Api.Domain.Entities.NhatKyHeThong", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EmailNguoiThucHien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HanhDong")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoaiThucTe")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Metadata")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiThucHienId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ThucTheId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserAgent")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HanhDong", "NgayTao");

                    b.HasIndex("LoaiThucTe", "ThucTheId");

                    b.HasIndex("NguoiThucHienId", "NgayTao");

                    b.ToTable("NhatKyHeThong", (string)null);
                });

            modelBuilder.Entity("LMS.Api.Domain.Entities.RutTienGiangVien", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ChuTaiKhoan")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("GiangVienId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SoTaiKhoan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SoTien")
                        .HasColumnType("int");

                    b.Property<string>("TenNganHang")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("COMPLETED");

                    b.HasKey("Id");

                    b.HasIndex("GiangVienId", "NgayTao");

                    b.ToTable("RutTienGiangVien", (string)null);
                });

            modelBuilder.Entity("LMS.Api.Domain.Entities.SuKien", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AnhUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaDiem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DiemYeuCau")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Format")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("OFFLINE");

                    b.Property<string>("GiangVienId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LinkThamGia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoaiSuKien")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("WORKSHOP");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("SucChua")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(50);

                    b.Property<DateTime>("ThoiGianBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ThoiGianKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValue("DRAFT");

                    b.HasKey("Id");

                    b.HasIndex("GiangVienId");

                    b.HasIndex("TrangThai", "ThoiGianBatDau");

                    b.ToTable("SuKien", (string)null);
                });

            modelBuilder.Entity("LMS.Api.Domain.Entities.SuKienAnh", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("AnhBia")
                        .HasColumnType("bit");

                    b.Property<string>("AnhUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("SuKienId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("SuKienId");

                    b.ToTable("SuKienAnh", (string)null);
                });

            modelBuilder.Entity("LMS.Api.Domain.Entities.ThanhToan", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoaiTien")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("VND");

                    b.Property<string>("MaThanhToanNhaCungCap")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayHoanThanh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiDungId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NhaCungCap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhienNhaCungCapId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SoTien")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValue("PENDING");

                    b.HasKey("Id");

                    b.HasIndex("PhienNhaCungCapId")
                        .IsUnique();

                    b.HasIndex("NguoiDungId", "NgayTao");

                    b.HasIndex("TrangThai", "NgayTao");

                    b.ToTable("ThanhToan", (string)null);
                });

            modelBuilder.Entity("LMS.Api.Domain.Entities.ThongBao", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("DaDoc")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DocLuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DuongDan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoaiThongBao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Metadata")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiDungId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NguoiDungId", "DaDoc", "NgayTao");

                    b.ToTable("ThongBao", (string)null);
                });

            modelBuilder.Entity("LMS.Api.Domain.Entities.TienDoBaiHoc", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BaiHocId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("DaHoanThanh")
                        .HasColumnType("bit");

                    b.Property<int>("GiayDaXem")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayHoanThanh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiDungId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("TyLeHoanThanh")
                        .HasColumnType("float");

                    b.Property<int>("ViTriXemCuoiGiay")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BaiHocId");

                    b.HasIndex("NguoiDungId");

                    b.HasIndex("NguoiDungId", "BaiHocId")
                        .IsUnique();

                    b.HasIndex("NguoiDungId", "DaHoanThanh");

                    b.ToTable("TienDoBaiHoc", (string)null);
                });

            modelBuilder.Entity("LMS.Api.Domain.Entities.TinNhan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CuocTroChuyenId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("GuiLuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiGuiId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("");

                    b.HasKey("Id");

                    b.HasIndex("CuocTroChuyenId");

                    b.HasIndex("GuiLuc");

                    b.HasIndex("NguoiGuiId");

                    b.ToTable("TinNhan", (string)null);
                });

            modelBuilder.Entity("LMS.Api.Domain.Entities.TinNhanDinhKem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("KichThuoc")
                        .HasColumnType("bigint");

                    b.Property<string>("LoaiNoiDung")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenFile")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenFileGoc")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("TinNhanId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TinNhanId");

                    b.ToTable("TinNhanDinhKem", (string)null);
                });

            modelBuilder.Entity("LMS.Api.Domain.Entities.BaiHoc", b =>
                {
                    b.HasOne("LMS.Api.Domain.Entities.ChuongHoc", "ChuongHoc")
                        .WithMany("CacBaiHoc")
                        .HasForeignKey("ChuongHocId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("LMS.Api.Domain.Entities.KhoaHoc", "KhoaHoc")
                        .WithMany("CacBaiHoc")
                        .HasForeignKey("KhoaHocId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ChuongHoc");

                    b.Navigation("KhoaHoc");
                });

            modelBuilder.Entity("LMS.Api.Domain.Entities.BaiKiemTra", b =>
                {
                    b.HasOne("LMS.Api.Domain.Entities.BaiHoc", "BaiHoc")
                        .WithOne("BaiKiemTra")
                        .HasForeignKey("LMS.Api.Domain.Entities.BaiKiemTra", "BaiHocId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("BaiHoc");
                });

            modelBuilder.Entity("LMS.Api.Domain.Entities.BaiNopKiemTra", b =>
                {
                    b.HasOne("LMS.Api.Domain.Entities.BaiKiemTra", "BaiKiemTra")
                        .WithMany("CacBaiNop")
                        .HasForeignKey("BaiKiemTraId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("LMS.Api.Domain.Entities.NguoiDung", "NguoiDung")
                        .WithMany("CacBaiNopKiemTra")
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("BaiKiemTra");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("LMS.Api.Domain.Entities.BaiTap", b =>
                {
                    b.HasOne("LMS.Api.Domain.Entities.BaiHoc", "BaiHoc")
                        .WithMany("CacBaiTap")
                        .HasForeignKey("BaiHocId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("LMS.Api.Domain.Entities.NguoiDung", "GiangVien")
                        .WithMany()
                        .HasForeignKey("GiangVienId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("LMS.Api.Domain.Entities.KhoaHoc", "KhoaHoc")
                        .WithMany("CacBaiTap")
                        .HasForeignKey("KhoaHocId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("BaiHoc");

                    b.Navigation("GiangVien");

                    b.Navigation("KhoaHoc");
                });

            modelBuilder.Entity("LMS.Api.Domain.Entities.BinhLuan", b =>
                {
                    b.HasOne("LMS.Api.Domain.Entities.BaiHoc", "BaiHoc")
                        .WithMany("CacBinhLuan")
                        .HasForeignKey("BaiHocId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("LMS.Api.Domain.Entities.BinhLuan", "BinhLuanCha")
                        .WithMany("CacPhanHoi")
                        .HasForeignKey("BinhLuanChaId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("LMS.Api.Domain.Entities.NguoiDung", "NguoiDung")
                        .WithMany("CacBinhLuan")
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("BaiHoc");

                    b.Navigation("BinhLuanCha");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("LMS.Api.Domain.Entities.CauHoiKiemTra", b =>
                {
                    b.HasOne("LMS.Api.Domain.Entities.BaiKiemTra", "BaiKiemTra")
                        .WithMany("CacCauHoi")
                        .HasForeignKey("BaiKiemTraId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("BaiKiemTra");
                });

            modelBuilder.Entity("LMS.Api.Domain.Entities.ChungChi", b =>
                {
                    b.HasOne("LMS.Api.Domain.Entities.KhoaHoc", "KhoaHoc")
                        .WithMany("CacChungChi")
                        .HasForeignKey("KhoaHocId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("LMS.Api.Domain.Entities.NguoiDung", "NguoiDung")
                        .WithMany("CacChungChi")
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("KhoaHoc");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("LMS.Api.Domain.Entities.ChuongHoc", b =>
                {
                    b.HasOne("LMS.Api.Domain.Entities.KhoaHoc", "KhoaHoc")
                        .WithMany("CacChuongHoc")
                        .HasForeignKey("KhoaHocId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("KhoaHoc");
                });

            modelBuilder.Entity("LMS.Api.Domain.Entities.DangKySuKien", b =>
                {
                    b.HasOne("LMS.Api.Domain.Entities.NguoiDung", "NguoiDung")
                        .WithMany("CacDangKySuKien")
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("LMS.Api.Domain.Entities.SuKien", "Event")
                        .WithMany("CacDangKy")
                        .HasForeignKey("SuKienId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("LMS.Api.Domain.Entities.DanhGiaKhoaHoc", b =>
                {
                    b.HasOne("LMS.Api.Domain.Entities.KhoaHoc", "KhoaHoc")
                        .WithMany("CacDanhGia")
                        .HasForeignKey("KhoaHocId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("LMS.Api.Domain.Entities.NguoiDung", "NguoiDung")
                        .WithMany("CacDanhGia")
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("KhoaHoc");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("LMS.Api.Domain.Entities.DoiThuongSuKien", b =>
                {
                    b.HasOne("LMS.Api.Domain.Entities.NguoiDung", "NguoiDung")
                        .WithMany("CacDoiThuongSuKien")
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("LMS.Api.Domain.Entities.DonMua", b =>
                {
                    b.HasOne("LMS.Api.Domain.Entities.KhoaHoc", "KhoaHoc")
                        .WithMany("CacDonMua")
                        .HasForeignKey("KhoaHocId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("LMS.Api.Domain.Entities.MaGiamGia", "MaGiamGia")
                        .WithMany()
                        .HasForeignKey("MaGiamGiaId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("LMS.Api.Domain.Entities.NguoiDung", "NguoiDung")
                        .WithMany("CacDonMua")
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("KhoaHoc");

                    b.Navigation("MaGiamGia");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("LMS.Api.Domain.Entities.GhiDanh", b =>
                {
                    b.HasOne("LMS.Api.Domain.Entities.KhoaHoc", "KhoaHoc")
                        .WithMany("CacGhiDanh")
                        .HasForeignKey("KhoaHocId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("LMS.Api.Domain.Entities.NguoiDung", "NguoiDung")
                        .WithMany("CacGhiDanh")
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("KhoaHoc");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("LMS.Api.Domain.Entities.GiaoDichVi", b =>
                {
                    b.HasOne("LMS.Api.Domain.Entities.DonMua", "DonMua")
                        .WithMany("CacGiaoDichVi")
                        .HasForeignKey("DonMuaId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("LMS.Api.Domain.Entities.KhoaHoc", "KhoaHoc")
                        .WithMany("CacGiaoDichVi")
                        .HasForeignKey("KhoaHocId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("LMS.Api.Domain.Entities.NguoiDung", "NguoiDung")
                        .WithMany("CacGiaoDichVi")
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("LMS.Api.Domain.Entities.ThanhToan", "ThanhToan")
                        .WithMany("CacGiaoDichVi")
                        .HasForeignKey("ThanhToanId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("DonMua");

                    b.Navigation("KhoaHoc");

                    b.Navigation("NguoiDung");

                    b.Navigation("ThanhToan");
                });

            modelBuilder.Entity("LMS.Api.Domain.Entities.KhoaHoc", b =>
                {
                    b.HasOne("LMS.Api.Domain.Entities.DanhMuc", "DanhMuc")
                        .WithMany("CacKhoaHoc")
                        .HasForeignKey("DanhMucId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LMS.Api.Domain.Entities.NguoiDung", "GiangVien")
                        .WithMany("CacKhoaHoc")
                        .HasForeignKey("GiangVienId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("DanhMuc");

                    b.Navigation("GiangVien");
                });

            modelBuilder.Entity("LMS.Api.Domain.Entities.KhoaHocDaLuu", b =>
                {
                    b.HasOne("LMS.Api.Domain.Entities.KhoaHoc", "KhoaHoc")
                        .WithMany("CacNguoiDungDaLuu")
                        .HasForeignKey("KhoaHocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LMS.Api.Domain.Entities.NguoiDung", "NguoiDung")
                        .WithMany("CacKhoaHocDaLuu")
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhoaHoc");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("LMS.Api.Domain.Entities.LichSuDungMaGiamGia", b =>
                {
                    b.HasOne("LMS.Api.Domain.Entities.DonMua", "DonMua")
                        .WithOne()
                        .HasForeignKey("LMS.Api.Domain.Entities.LichSuDungMaGiamGia", "DonMuaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("LMS.Api.Domain.Entities.KhoaHoc", "KhoaHoc")
                        .WithMany()
                        .HasForeignKey("KhoaHocId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("LMS.Api.Domain.Entities.MaGiamGia", "MaGiamGia")
                        .WithMany("CacLuotSuDung")
                        .HasForeignKey("MaGiamGiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LMS.Api.Domain.Entities.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("DonMua");

                    b.Navigation("KhoaHoc");

                    b.Navigation("MaGiamGia");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("LMS.Api.Domain.Entities.MaGiamGia", b =>
                {
                    b.HasOne("LMS.Api.Domain.Entities.NguoiDung", "GiangVien")
                        .WithMany()
                        .HasForeignKey("GiangVienId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("LMS.Api.Domain.Entities.KhoaHoc", "KhoaHoc")
                        .WithMany("CacMaGiamGia")
                        .HasForeignKey("KhoaHocId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("GiangVien");

                    b.Navigation("KhoaHoc");
                });

            modelBuilder.Entity("LMS.Api.Domain.Entities.NguoiNhanMaGiamGia", b =>
                {
                    b.HasOne("LMS.Api.Domain.Entities.NguoiDung", "GiangVien")
                        .WithMany()
                        .HasForeignKey("GiangVienId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("LMS.Api.Domain.Entities.MaGiamGia", "MaGiamGia")
                        .WithMany("CacNguoiNhan")
                        .HasForeignKey("MaGiamGiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LMS.Api.Domain.Entities.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("LMS.Api.Domain.Entities.KhoaHoc", "SourceCourse")
                        .WithMany()
                        .HasForeignKey("SourceCourseId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("GiangVien");

                    b.Navigation("MaGiamGia");

                    b.Navigation("NguoiDung");

                    b.Navigation("SourceCourse");
                });

            modelBuilder.Entity("LMS.Api.Domain.Entities.NguoiThamGiaTroChuyen", b =>
                {
                    b.HasOne("LMS.Api.Domain.Entities.CuocTroChuyen", "CuocTroChuyen")
                        .WithMany("CacNguoiThamGia")
                        .HasForeignKey("CuocTroChuyenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LMS.Api.Domain.Entities.NguoiDung", "NguoiDung")
                        .WithMany("Conversations")
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CuocTroChuyen");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("LMS.Api.Domain.Entities.RutTienGiangVien", b =>
                {
                    b.HasOne("LMS.Api.Domain.Entities.NguoiDung", "GiangVien")
                        .WithMany("InstructorWithdrawals")
                        .HasForeignKey("GiangVienId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("GiangVien");
                });

            modelBuilder.Entity("LMS.Api.Domain.Entities.SuKien", b =>
                {
                    b.HasOne("LMS.Api.Domain.Entities.NguoiDung", "GiangVien")
                        .WithMany("CacSuKienToChuc")
                        .HasForeignKey("GiangVienId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("GiangVien");
                });

            modelBuilder.Entity("LMS.Api.Domain.Entities.SuKienAnh", b =>
                {
                    b.HasOne("LMS.Api.Domain.Entities.SuKien", "SuKien")
                        .WithMany("CacHinhAnh")
                        .HasForeignKey("SuKienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SuKien");
                });

            modelBuilder.Entity("LMS.Api.Domain.Entities.ThanhToan", b =>
                {
                    b.HasOne("LMS.Api.Domain.Entities.NguoiDung", "NguoiDung")
                        .WithMany("ExternalPayments")
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("LMS.Api.Domain.Entities.ThongBao", b =>
                {
                    b.HasOne("LMS.Api.Domain.Entities.NguoiDung", "NguoiDung")
                        .WithMany("CacThongBao")
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("LMS.Api.Domain.Entities.TienDoBaiHoc", b =>
                {
                    b.HasOne("LMS.Api.Domain.Entities.BaiHoc", "BaiHoc")
                        .WithMany("CacTienDoBaiHoc")
                        .HasForeignKey("BaiHocId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("LMS.Api.Domain.Entities.NguoiDung", "NguoiDung")
                        .WithMany("CacTienDoBaiHoc")
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("BaiHoc");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("LMS.Api.Domain.Entities.TinNhan", b =>
                {
                    b.HasOne("LMS.Api.Domain.Entities.CuocTroChuyen", "CuocTroChuyen")
                        .WithMany("CacTinNhan")
                        .HasForeignKey("CuocTroChuyenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LMS.Api.Domain.Entities.NguoiDung", "NguoiGui")
                        .WithMany("CacTinNhanDaGui")
                        .HasForeignKey("NguoiGuiId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CuocTroChuyen");

                    b.Navigation("NguoiGui");
                });

            modelBuilder.Entity("LMS.Api.Domain.Entities.TinNhanDinhKem", b =>
                {
                    b.HasOne("LMS.Api.Domain.Entities.TinNhan", "TinNhan")
                        .WithMany("CacFileDinhKem")
                        .HasForeignKey("TinNhanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TinNhan");
                });

            modelBuilder.Entity("LMS.Api.Domain.Entities.BaiHoc", b =>
                {
                    b.Navigation("BaiKiemTra");

                    b.Navigation("CacBaiTap");

                    b.Navigation("CacBinhLuan");

                    b.Navigation("CacTienDoBaiHoc");
                });

            modelBuilder.Entity("LMS.Api.Domain.Entities.BaiKiemTra", b =>
                {
                    b.Navigation("CacBaiNop");

                    b.Navigation("CacCauHoi");
                });

            modelBuilder.Entity("LMS.Api.Domain.Entities.BinhLuan", b =>
                {
                    b.Navigation("CacPhanHoi");
                });

            modelBuilder.Entity("LMS.Api.Domain.Entities.ChuongHoc", b =>
                {
                    b.Navigation("CacBaiHoc");
                });

            modelBuilder.Entity("LMS.Api.Domain.Entities.CuocTroChuyen", b =>
                {
                    b.Navigation("CacNguoiThamGia");

                    b.Navigation("CacTinNhan");
                });

            modelBuilder.Entity("LMS.Api.Domain.Entities.DanhMuc", b =>
                {
                    b.Navigation("CacKhoaHoc");
                });

            modelBuilder.Entity("LMS.Api.Domain.Entities.DonMua", b =>
                {
                    b.Navigation("CacGiaoDichVi");
                });

            modelBuilder.Entity("LMS.Api.Domain.Entities.KhoaHoc", b =>
                {
                    b.Navigation("CacBaiHoc");

                    b.Navigation("CacBaiTap");

                    b.Navigation("CacChungChi");

                    b.Navigation("CacChuongHoc");

                    b.Navigation("CacDanhGia");

                    b.Navigation("CacDonMua");

                    b.Navigation("CacGhiDanh");

                    b.Navigation("CacGiaoDichVi");

                    b.Navigation("CacMaGiamGia");

                    b.Navigation("CacNguoiDungDaLuu");
                });

            modelBuilder.Entity("LMS.Api.Domain.Entities.MaGiamGia", b =>
                {
                    b.Navigation("CacLuotSuDung");

                    b.Navigation("CacNguoiNhan");
                });

            modelBuilder.Entity("LMS.Api.Domain.Entities.NguoiDung", b =>
                {
                    b.Navigation("CacBaiNopKiemTra");

                    b.Navigation("CacBinhLuan");

                    b.Navigation("CacChungChi");

                    b.Navigation("CacDangKySuKien");

                    b.Navigation("CacDanhGia");

                    b.Navigation("CacDoiThuongSuKien");

                    b.Navigation("CacDonMua");

                    b.Navigation("CacGhiDanh");

                    b.Navigation("CacGiaoDichVi");

                    b.Navigation("CacKhoaHoc");

                    b.Navigation("CacKhoaHocDaLuu");

                    b.Navigation("CacSuKienToChuc");

                    b.Navigation("CacThongBao");

                    b.Navigation("CacTienDoBaiHoc");

                    b.Navigation("CacTinNhanDaGui");

                    b.Navigation("Conversations");

                    b.Navigation("ExternalPayments");

                    b.Navigation("InstructorWithdrawals");
                });

            modelBuilder.Entity("LMS.Api.Domain.Entities.SuKien", b =>
                {
                    b.Navigation("CacDangKy");

                    b.Navigation("CacHinhAnh");
                });

            modelBuilder.Entity("LMS.Api.Domain.Entities.ThanhToan", b =>
                {
                    b.Navigation("CacGiaoDichVi");
                });

            modelBuilder.Entity("LMS.Api.Domain.Entities.TinNhan", b =>
                {
                    b.Navigation("CacFileDinhKem");
                });
#pragma warning restore 612, 618
        }
    }
}
